#!/bin/bash

#COLOUR
cyan='\e[0;36m'
green='\e[0;32m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[0;33m'
BlueF='\e[1;34m' #Biru
RESET="\033[00m" #normal
orange='\e[38;5;166m'

echoSep(){
  echo -e "$1" "+---------------------------------+"
}

banner(){
  echo "                        _                                       "
  echo -e "$red""   ___ _ __ _   _ _ __ | |_ ___ _ _ _ __ ___   __ _  __ _  ___  "
  echo -e "$orange""  / __| '__| | | | '_ \| __/ _ \| || '_ \` _ \ / _\` |/ _\` |/ _ \ "
  echo -e "$yellow"" | (__| |  | |_| | |_) | || (_) | || | | | | | (_| | (_| |  __/ "
  echo -e "$lightgreen""  \___|_|   \__, | .__/ \__\___/___|_| |_| |_|\__,_|\__, |\___| "
  echo -e "$green""            |___/|_|                                |___/       "
  echo -e "$orange""                                                  ______________"
  echo -e "$BlueF""                                                    by h4shell  "
}

banner

if [ $# -eq 0 ]; then
  echo
  echoSep "$green"
  echo
  echo -e -n "inserire il "$BlueF"segreto$green: " && read secret
  echo
  echoSep "$green"
  echo
  echo -e -n "inserire la "$BlueF"password$green: " && read -s pwd
  echo
  echo
  echoSep
  ls *.jpg *.jpeg 2>/dev/null
  echoSep "$green"
  echo -e -n "inserisci il" $BlueF"file di immagine$green (opzionale): " && read imgfile
  enc=$(echo $secret | gpg --symmetric --cipher-algo AES256 --batch --passphrase $pwd --armor | base64 -w 0)
  if [ -z $imgfile ]; then
    echo
    echoSep "$green"
    echo
    echo -e -n "$orange" ${enc}
    echo
    echo
    echoSep "$green"
    echo
  else
    exiftool -Comment=$enc $imgfile
  fi

else
  echo $1 | base64 -d > /tmp/s.gpg && gpg --decrypt /tmp/s.gpg && rm /tmp/s.gpg
fi